module.exports.descriptors=[
'Warner', 
'East Natchitoches',
'Lyon', 
'Willow Run', 
'Conyersville', 
'Mount Baker', 
'Farmington Lake', 
'Martins Corner', 
'Pickerel Narrows', 
'Willaha', 
'Center', 
'Spring City',
'Mittenlane', 
'East Waterford', 
'Coltman', 
'Scottsville', 
'Hebron', 
'Longview', 
'Emerson', 
'North Knoxville'
]
module.exports.places=[
    'Momford Landing',
'Ipswich',
'Storms',
'Kalauao',
'Farwell',
'Brentwood Village',
'Wilhelm Park',
'Bannister Acres',
'Bent Pine',
'Mitchell',
'Social Circle',
'Kreutzberg',
'Cimarron',
'Brookhaven',
'Montverde Junction', 
'Midland City',
'Sacramento',
'Del Rey Oaks',
'Coal Creek',
'Rabbitown'
]

